---
basic_ingest.settings:
  type: config_object
  mapping:
    map:
      type: sequence
      label: Mapping of model URIs to media type IDs.
      sequence:
        type: mapping
        mapping:
          uri:
            type: uri
          media_type:
            type: string
          display_hints:
            type: sequence
            nullable: true
            sequence:
              type: uri
